ota:
  - platform: esphome
    id: !extend ota_esphome
    password: !secret "kitchen_voice_pe_ota_password"

esphome:
  name: kitchen-voice-pe
  friendly_name: Kitchen Voice PE
  name_add_mac_suffix: false

packages:
  additions:
    url: https://github.com/JohnTheNerd/home-assistant-voice-pe-configs
    files:
      - path: voice-pe-additions.yaml
    ref: master
    refresh: 0s