substitutions:
  name: "office-atom-echo"
  friendly_name: "Office Atom Echo"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.9.0
  project:
    name: esphome.bluetooth-proxy
    version: "24.7.4.1"

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

dashboard_import:
  package_import_url: github://esphome/firmware/bluetooth-proxy/m5stack-atom-lite.yaml@main

logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret "office_atom_echo_ota_password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: true

bluetooth_proxy:
  active: true

captive_portal:
